config/routes.rb
Rails.application.routes.draw do

  get 'company/disclaimer', to: 'company#disclaimer'

  get 'company/news', to: 'company#news'

  get 'company/faqs', to: 'company#faqs'

  get 'company/privacy', to: 'company#privacy'

  get 'company/terms_conditions', to: 'company#terms_conditions'

  get 'company/corporate_responsibility', to: 'company#corporate_responsibility'

  get 'company/services', to: 'company#services'

  resources :cvs
  root 'pages#home'

  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'

  devise_for :users, 
             :path => '',
             :path_names => {:sign_in => 'log_in', :sign_out => 'logout', :edit => 'profile'},
             :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                              :registrations => 'registrations'}

resources :users, only: [:show, :edit]
resources :jobs
resources :photos

resources :jobs do
  resources :japplications, only: [:create]
end

end

app/views/shared/_banner.html.erb
<div class = "row">
<div class="banner">
        
        <div class = "container">
        <div class = "col s12">

        <p class = "intro-big-header"> Find available jobs online.

        </p>
        <p>  
        <%= link_to "Find Job", jobs_path, :class => "btn btn-primary" %>
      	<%= link_to "Post Job", new_job_path, :class => "btn btn-primary" %>
      
      </p>
      

        <h2>Search available jobs from offices over 34,000 cities and 192 countries.</h2>   
        </div>
        </div>

        </div>

</div> 

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type= "text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end%>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
 		<% flash.each do |f| %> 
 			<% type =  f[0].to_s.gsub('alert','error').gsub('notice','info') %>
 			toastr['<%= type %>']('<%= f[1] %>')
 		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">JOBPORTAL</a>
        </div>
       
          

        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav navbar-right">



            <% if(!user_signed_in?) %>
              <li><%= link_to "Log In", new_user_session_path %></li>
              <li><%= link_to "Sign Up", new_user_registration_path %></li>
            <% else %>
           
            <li><!-- search facility --> 
               <p><%= form_tag(jobs_path, method: :get) do %>
                  <%= text_field_tag :term %>
                  <%= submit_tag 'Search' %>
                  <% end %>
                    
                  </p>
             </li>
      

             <li>
             <a href="#"><i class="fa fa-folder-open-o"></i> Become an Employer</a>
             </li>
            
             <li>
             <a href="#"><i class="fa fa-envelope" aria-hidden="true"></i>Messages</a>
             </li>



            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %> &nbsp;
              <%= current_user.fullname %> <span class="caret"></span>
              </a>


              <ul class="dropdown-menu">
                <li><%= link_to "Your CV", cvs_path %></li>
                <li><%= link_to "Find Job", jobs_path %></li>
                <li><a href="#">My Applications</a></li>
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li role="separator" class="divider"></li>
                <li><a href="#">Account Setting</a></li>
                <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
              </ul>
            </li>


            <% end %>  
            
           

          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> Help<span class="caret"></span></a>
               
              <ul class="dropdown-menu">
                <li><a href="#">How does it work</a></li>
                <li><a href="#">Cookies</a></li>
                <li><a href="#">Terms and Conditions</a></li>
                <li><a href="#">Contact us</a></li>
                <li><a href="#">FAQ</a></li>
              </ul>
           
            </li>
          </ul>
         
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    
    