config/routes.rb
Rails.application.routes.draw do

  get 'company/disclaimer', to: 'company#disclaimer'

  get 'company/news', to: 'company#news'

  get 'company/faqs', to: 'company#faqs'

  get 'company/privacy', to: 'company#privacy'

  get 'company/terms_conditions', to: 'company#terms_conditions'

  get 'company/corporate_responsibility', to: 'company#corporate_responsibility'

  get 'company/services', to: 'company#services'

  resources :cvs
  root 'pages#home'

  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'

  devise_for :users, 
             :path => '',
             :path_names => {:sign_in => 'log_in', :sign_out => 'logout', :edit => 'profile'},
             :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                              :registrations => 'registrations'}

resources :users, only: [:show, :edit]
resources :jobs
resources :photos

resources :jobs do
  resources :japplications, only: [:create]
end

end

app/models/cv.rb
class Cv < ActiveRecord::Base
end

app/controllers/cvs_controller.rb
class CvsController < ApplicationController
  before_action :set_cv, only: [:show, :edit, :update, :destroy]

  # GET /cvs
  # GET /cvs.json
  def index
    @cvs = Cv.all
  end

  # GET /cvs/1
  # GET /cvs/1.json
  def show
  end

  # GET /cvs/new
  def new
    @cv = Cv.new
  end

  # GET /cvs/1/edit
  def edit
  end

  # POST /cvs
  # POST /cvs.json
  def create
    @cv = Cv.new(cv_params)

    respond_to do |format|
      if @cv.save
        format.html { redirect_to @cv, notice: 'Cv was successfully created.' }
        format.json { render :show, status: :created, location: @cv }
      else
        format.html { render :new }
        format.json { render json: @cv.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cvs/1
  # PATCH/PUT /cvs/1.json
  def update
    respond_to do |format|
      if @cv.update(cv_params)
        format.html { redirect_to @cv, notice: 'Cv was successfully updated.' }
        format.json { render :show, status: :ok, location: @cv }
      else
        format.html { render :edit }
        format.json { render json: @cv.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cvs/1
  # DELETE /cvs/1.json
  def destroy
    @cv.destroy
    respond_to do |format|
      format.html { redirect_to cvs_url, notice: 'Cv was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cv
      @cv = Cv.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cv_params
      params.require(:cv).permit(:name, :profession, :image, :email, :education, :experiences)
    end
end

app/helpers/cvs_helper.rb
module CvsHelper
end

app/views/cvs/_form.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Create your CV 
  </div>  
  <div class="panel-body">
    <div class="container">



<%= form_for(@cv) do |f| %>
  <% if @cv.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cv.errors.count, "error") %> prohibited this cv from being saved:</h2>

      <ul>
      <% @cv.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
          <div class="form-group">
            <label>Name</label>
            <%= f.text_field :name, placeholder: "FullName", class: "form-control" %>
          </div>
  </div>

  <div class="row">
          <div class="form-group">
            <label>Profession</label>
            <%= f.text_field :profession, placeholder: "Profession", class: "form-control" %>
          </div>
  </div>
  
  <div class="row">
          <div class="form-group">
            <label>Image</label>
            <%= f.text_field :image, placeholder: "Image_url", class: "form-control" %>
          </div>
  </div>
  

  <div class="row">
          <div class="form-group">
            <label>Email</label>
            <%= f.text_field :email, placeholder: "Email", class: "form-control" %>
          </div>
  </div>

  <div class="row">
          <div class="form-group">
            <label>Education</label>
            <%= f.text_area :education, placeholder: "Education", class: "form-control" %>
          </div>
  </div>

  <div class="row">
          <div class="form-group">
            <label>Experiences</label>
            <%= f.text_area :experiences, placeholder: "Experiences", class: "form-control" %>
          </div>
  </div>

  <div class="actions">
        <%= f.submit "Save", class: "btn btn-primary" %>
  </div>
  
<% end %>

</div>
</div>
</div>

app/views/cvs/edit.html.erb
<h1>Editing Cv</h1>

<%= render 'form' %>

<%= link_to 'Show', @cv %> |
<%= link_to 'Back', cvs_path %>

app/views/cvs/index.html.erb
<p id="notice"><%= notice %></p>
<div class="panel panel-default">

<div class="panel-body">

<h3>Listing Cvs</h3>
<p>Welcome to user profile section.
Please kindly create CV if not having one. Thank you</p>
<p>Best Regards,</p>
Your Admin.

<br>
<p>
<% @cvs.each do |cv| %>
<%= link_to 'Go to my CV', cv %>
<% end %>
</p>
<br>
<br>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Profession</th>
 </tr>
  </thead>
  <tbody>
    <% @cvs.each do |cv| %>
      <tr>
        <td><%= cv.name %></td>
        <td><%= cv.profession %></td>
        </tr>
        <tr>
        <td><%= link_to 'View', cv %></td>
        <td><%= link_to 'Edit', edit_cv_path(cv) %></td>
        <td><%= link_to 'Destroy', cv, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
     
    <% end %>
  </tbody>
</table>

<br>
<!-- View if user created-->
<%= link_to 'Create Cv', new_cv_path %>


</div>
</div>

app/views/cvs/new.html.erb
<h2>Personal Profile</h2>

<%= render 'form' %>

<%= link_to 'Back', cvs_path %>

app/views/cvs/show.html.erb
<p id="notice"><%= notice %></p>

<body>

    <div class="wrapper">
        <div class="sidebar-wrapper">
            <div class="profile-container">
                <%= image_tag(@cv.image) %> 
                <br>
                <br>
                
                <p><strong>Name:</strong><%= @cv.name %></p>
                <p><strong>Profession:</strong><br><%= @cv.profession %></p>
            </div><!--//profile-container-->
            
            <div class="contact-container container-block">
                <ul class="list-unstyled contact-list">
                    <li class="email"><a href="mailto: yourname@email.com"><strong>Email:</strong><%= @cv.email %></a></li>
                </ul>
            </div>


        </div>
        
        <div class="main-wrapper">
            
            <section class="section summary-section">
                <h2 class="section-title"><i class="fa fa-user"></i>Career Profile</h2>
                <div class="summary">
                
                    <p><%= @cv.education %></p>
                </div><!--//summary-->
            </section><!--//section-->
        


            <section class="section experiences-section">
                <h2 class="section-title"><i class="fa fa-briefcase"></i>Experiences</h2>
                
                <div class="item">
                    <div class="details">
                        <p><%= @cv.experiences %></p>
                    </div>
                </div>

            </section>
        </div>
    </div>
</body>
<%= link_to 'Edit', edit_cv_path(@cv) %> |
<%= link_to 'Back', cvs_path %>
        


 