config/routes.rb
Rails.application.routes.draw do

  get 'company/disclaimer', to: 'company#disclaimer'

  get 'company/news', to: 'company#news'

  get 'company/faqs', to: 'company#faqs'

  get 'company/privacy', to: 'company#privacy'

  get 'company/terms_conditions', to: 'company#terms_conditions'

  get 'company/corporate_responsibility', to: 'company#corporate_responsibility'

  get 'company/services', to: 'company#services'

  resources :cvs
  root 'pages#home'

  get  '/about',   to: 'pages#about'
  get  '/contact', to: 'pages#contact'

  devise_for :users, 
             :path => '',
             :path_names => {:sign_in => 'log_in', :sign_out => 'logout', :edit => 'profile'},
             :controllers => {:omniauth_callbacks => 'omniauth_callbacks',
                              :registrations => 'registrations'}

resources :users, only: [:show, :edit]
resources :jobs
resources :photos

resources :jobs do
  resources :japplications, only: [:create]
end

end

app/views/layouts/_footer.html.erb
<footer class = "footer">

<ul class="nav navbar-nav navbar-left">
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Disclaimer", company_disclaimer_path %></li>
	
		<li><%= link_to "About Us", about_path %></li>
		
		<li><%= link_to "News", company_news_path %></a> </li>
		<li><%= link_to "FaQs", company_faqs_path %></li>
		<li><%= link_to "Privacy Policy", company_privacy_path %></li>
		<li><%= link_to "Terms & Conditions", company_terms_conditions_path %></li>
		<li><%= link_to "Corporate Responsibility", company_corporate_responsibility_path %></li>
		<li><%= link_to "Contact Us", contact_path %></li>
		<li><%= link_to "Services", company_services_path %></li>
	
	</ul>


</footer>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Jobportal</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
 

</head>
<body>

       <%= render 'shared/navbar' %>
<% if request.original_url == root_url %>  
<%= render 'shared/banner' %>     
<% end %>

 
      <%= render 'shared/message' %>
<div class="container">
<%= yield %>
		
</div>

</body>
<%= render 'layouts/footer'%>
</html>